# Generated by Django 5.1.3 on 2024-11-06 16:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2024, 11, 6, 13, 20, 11, 464885))),
                ('data_atualizacao', models.DateTimeField(default=datetime.datetime(2024, 11, 6, 13, 20, 11, 464900))),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('GASTO', 'Gasto'), ('INVESTIMENTO', 'Investimento')], default='', max_length=20)),
                ('categoria', models.CharField(choices=[('DOMESTICO', 'Doméstico'), ('TRANSPORTE', 'Transporte'), ('COMIDA', 'Comida'), ('ENTRETENIMENTO', 'Entretenimento'), ('SAUDE', 'Saúde'), ('UTILIDADE', 'Utilidade'), ('SALARIO', 'Salário'), ('EDUCACAO', 'Educação'), ('OUTRO', 'Outro')], default='', max_length=20)),
                ('metodo_pagamento', models.CharField(choices=[('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('TRANSFERENCIA', 'Transferência Bancária'), ('BOLETO', 'Boleto Bancário'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('OUTRO', 'Outro')], default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
